language: android
sudo: false # faster builds

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
jdk: oraclejdk8

script:
  - ./gradlew assembleRelease
  - ./gradlew test

after_success:
  - bash <(curl -s https://codecov.io/bash)
